/home/pi/logs/chromium.log
/home/pi/logs/slideshow.log
/home/pi/logs/system-health.log
{
    daily
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    size 10M
    copytruncate
}
